apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: config
  namespace: default
spec:
  interval: 1m
  releaseName: config
  chart:
    spec:
      chart: config
      version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: online-store-repo
        namespace: flux-system